import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'bhf-eblup',
  displayName: 'Battese–Harter–Fuller EBLUP (Unit-Level)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'both',
  rPackage: 'sae',
  rFunction: 'eblupBHF / pbmseBHF',
  stataPackage: 'base mixed',
  stataCommand: 'mixed',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'The canonical unit-level SAE model. Fits a linear mixed model with area random effects ' +
    'to the survey microdata, then uses the estimated model to predict area means for all ' +
    'areas (sampled and unsampled), combining individual predictions with the random area effect. ' +
    'Requires population means of auxiliary variables for all target areas.',
  whyChooseThis:
    'Choose BHF when you have household/unit-level survey data and know the population means ' +
    'of your auxiliary variables from a census or administrative source. It is the standard ' +
    'unit-level method and is well supported in both R and Stata.',
  assumptions: [
    'Linear relationship between target and auxiliary variables at the unit level.',
    'Area random effects are normally distributed.',
    'Unit-level errors are normally distributed and homoscedastic.',
    'Population means of auxiliaries are known without error for all target areas.',
    'At least some sampled units in each area (out-of-sample: synthetic predictor only).',
  ],
  references: [
    'Battese, G.E., Harter, R.M. & Fuller, W.A. (1988). JASA 83, 28–36.',
    'Rao & Molina (2015). Small Area Estimation, 2nd ed. Ch. 7.',
    'Molina, I. & Marhuenda, Y. (2015). The R Journal 7(1). [sae package]',
  ],
  rTemplate: `# ============================================================
# Battese–Harter–Fuller Nested-Error EBLUP (Unit-Level)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Battese, Harter & Fuller (1988)
# R package: sae
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level population means of auxiliaries)
# ============================================================

if (!requireNamespace("sae", quietly = TRUE)) install.packages("sae")
library(sae)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")
# census_data must have: {{AREA_ID}}, population size (Ni), and means of {{AUX_VARS_R}}

# Area population means matrix (columns = auxiliary variable means, rows = areas)
aux_vars <- c({{AUX_VARS_R}})   # e.g. c("x1", "x2")
meanxpop <- census_data[, c("{{AREA_ID}}", aux_vars)]
popnsize  <- data.frame(area = census_data\${{AREA_ID}},
                        Ni   = census_data$Ni)

bhf_result <- eblupBHF(
  formula  = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  dom      = survey_data\${{AREA_ID}},
  meanxpop = meanxpop,
  popnsize = popnsize,
  method   = "REML",
  data     = survey_data
)

# Parametric bootstrap MSE
bhf_mse <- pbmseBHF(
  formula  = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  dom      = survey_data\${{AREA_ID}},
  meanxpop = meanxpop,
  popnsize = popnsize,
  B        = {{N_SIM}},
  data     = survey_data
)

results <- data.frame(
  area  = bhf_result$eblup$domain,
  eblup = bhf_result$eblup$eblup,
  mse   = bhf_mse$mse$mse,
  cv    = sqrt(bhf_mse$mse$mse) / bhf_result$eblup$eblup
)
print(results)
`,
  stataTemplate: `* ============================================================
* Battese–Harter–Fuller Nested-Error EBLUP (Unit-Level)
* Generated by SAE Syntax Generator on {{DATE}}
* Uses base Stata \`mixed\` — compatible with Stata 14+
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear

* Fit the nested-error linear mixed model
mixed {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, reml

* Extract random effects (BLUPs) and fixed-effect predictions
predict xb_fixed, xb
predict u_area, reffects

* Predicted small area mean = fixed-effect prediction + BLUP of area effect
gen predicted_mean = xb_fixed + u_area

* NOTE: To get EBLUP for all areas (including unsampled), merge with census
* population means and apply: predicted = beta_hat * x_bar_pop + u_hat (0 for OOS)
`,
}

export default entry
