import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'direct',
  displayName: 'Direct Estimator (Design-Based Benchmark)',
  level: 'model-assisted',
  inferenceType: 'design-based',
  targetTypes: ['continuous', 'binary', 'proportion', 'count'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'none',
    weights: true,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'prasad-rao',
  rPackage: 'survey',
  rFunction: 'svyby / svymean',
  stataPackage: 'base',
  stataCommand: 'svy: mean',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'Estimates the area mean or total directly from sample observations within each area ' +
    'using survey design weights. No auxiliary data or modelling assumptions are required. ' +
    'Precision is low when area sample sizes are small — this is why SAE methods are needed.',
  whyChooseThis:
    'Use this as a benchmark to check whether model-based estimates are reasonable. ' +
    'If your sample sizes are large enough (ni ≥ 25 per area), direct estimates may be ' +
    'sufficient on their own.',
  assumptions: [
    'Sample sizes within each area are large enough for reliable direct estimation.',
    'Survey weights correctly reflect the sampling design.',
  ],
  references: [
    'Kish, L. (1965). Survey Sampling. Wiley. https://www.wiley.com/en-gb/Survey+Sampling-p-9780471489009',
    'Cochran, W.G. (1977). Sampling Techniques, 3rd ed. Wiley. https://www.wiley.com/en-gb/Sampling+Techniques%2C+3rd+Edition-p-9780471162407',
    'survey package for R (Lumley, T.). https://cran.r-project.org/package=survey',
  ],
  rTemplate: `# ============================================================
# Direct Estimator — Design-Based Benchmark
# Generated by SAE Syntax Generator on {{DATE}}
# Survey data: {{SURVEY_DATA}}
# ============================================================

# Install required packages if not already installed
if (!requireNamespace("survey", quietly = TRUE)) install.packages("survey")
library(survey)

# Load survey microdata
survey_data <- read.csv("{{SURVEY_DATA}}")

# Define the survey design (adjust strata/cluster/fpc as appropriate)
design <- svydesign(
  ids     = ~1,                        # replace ~1 with cluster variable if clustered
  weights = ~{{WEIGHT_VAR}},
  data    = survey_data
)

# Compute direct estimates by small area
direct_estimates <- svyby(
  formula  = ~{{TARGET_VAR}},
  by       = ~{{AREA_ID}},
  design   = design,
  FUN      = svymean,
  keep.var = TRUE
)

print(direct_estimates)

# NOTE: SE column gives the standard error; CV = SE / estimate.
# Areas with CV > 0.25 typically warrant model-based SAE methods.
`,
  stataTemplate: `* ============================================================
* Direct Estimator — Design-Based Benchmark
* Generated by SAE Syntax Generator on {{DATE}}
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear

* Declare survey design (adjust psu/strata as appropriate)
svyset [pweight = {{WEIGHT_VAR}}]

* Direct estimates by small area
svy: mean {{TARGET_VAR}}, over({{AREA_ID}})

* Coefficient of variation: CV > 0.25 suggests SAE methods are needed
`,
}

export default entry
