import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'ebp-censuseb',
  displayName: 'Empirical Best Predictor / CensusEB (Unit-Level, Poverty Mapping)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['poverty', 'continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'unit',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'bootstrap',
  rPackage: 'emdi / povmap / sae',
  rFunction: 'ebp (emdi/povmap) / ebBHF + pbmseebBHF (sae)',
  stataPackage: 'World Bank sae package',
  stataCommand: 'sae model / sae sim',
  stataMinVersion: 17,
  stataV14Fallback:
    '* The World Bank sae/povmap package requires Stata 17+.\n' +
    '* For Stata 14, run the R script instead (emdi/povmap packages).\n' +
    '* Alternatively, use the base BHF-EBLUP (mixed) as an approximation for means only:\n' +
    '* mixed {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, reml',
  plainDescription:
    'The current best-practice method for poverty mapping. Simulates the full welfare ' +
    'distribution onto census microdata using a model fitted on the survey, enabling ' +
    'estimation of non-linear poverty and inequality indicators (headcount, poverty gap, ' +
    'Gini). MSE is estimated by parametric bootstrap. Requires unit-level census auxiliaries.',
  whyChooseThis:
    'Use this when your target is a poverty rate, a poverty gap, the Gini coefficient, ' +
    'or any other non-linear function of a welfare variable. It is the standard method ' +
    'recommended by the World Bank and endorsed by Corral et al. (2022).',
  assumptions: [
    'Normality of model residuals (or apply a Box–Cox transformation).',
    'The unit-level model fitted on the survey is valid for the census population.',
    'Unit-level auxiliary variables in the survey are comparable to those in the census.',
    'No informative sampling given the model covariates.',
  ],
  references: [
    'Molina, I. & Rao, J.N.K. (2010). Canadian Journal of Statistics 38, 369–385.',
    'Corral, P., Molina, I., Cojocaru, A. & Segovia, S. (2022). Guidelines to SAE for Poverty Mapping. World Bank. http://hdl.handle.net/10986/37728',
    'Kreutzmann, A.-K. et al. (2019). The R Journal 11(1). [emdi package]',
    'povmap package: https://cran.r-project.org/package=povmap',
  ],
  caveats: [
    'Stata implementation requires v17+; use R (emdi/povmap) for Stata 14 users.',
    'Computationally intensive for large census files and many bootstrap replications.',
    'If census data are unavailable, the ELL method (id: ell) is an alternative.',
  ],
  rTemplate: `# ============================================================
# Empirical Best Predictor / CensusEB — Poverty Mapping
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Molina & Rao (2010); Corral et al. (2022)
# R packages: povmap / emdi
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (unit-level)
# ============================================================

if (!requireNamespace("povmap", quietly = TRUE)) install.packages("povmap")
library(povmap)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")

# Fit EBP using povmap (extends emdi with poverty-mapping features)
ebp_result <- ebp(
  fixed       = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  pop_data    = census_data,
  pop_domains = "{{AREA_ID}}",
  smp_data    = survey_data,
  smp_domains = "{{AREA_ID}}",
  B           = {{N_SIM}},              # bootstrap replications for MSE
  transformation = "log",               # "log", "arcsin", or "no"
  MSE         = TRUE
)

summary(ebp_result)
# Indicators include: Mean, Gini, FGT0 (headcount), FGT1 (gap), FGT2 (severity)
print(estimators(ebp_result, indicator = "FGT0"))  # poverty headcount
`,
  stataTemplate: `* ============================================================
* Empirical Best Predictor / CensusEB — Poverty Mapping
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Molina & Rao (2010); Corral et al. (2022)
* Stata package: World Bank sae (requires Stata 17+)
* Survey data: {{SURVEY_DATA}}
* Census data: {{CENSUS_DATA}} (unit-level)
* ============================================================

* Install World Bank sae package if not available:
* ssc install sae

use "{{SURVEY_DATA}}", clear

* Step 1: Fit the EBP model on survey data
sae model {{TARGET_VAR}} {{AUX_VARS_STATA}}, area({{AREA_ID}})

* Step 2: Simulate onto the census to produce poverty indicators
sae sim, census("{{CENSUS_DATA}}") ///
    area({{AREA_ID}}) ///
    bootstrap({{N_SIM}}) ///
    poverty(fgt0 fgt1 fgt2 gini)

* Inspect results
list
`,
}

export default entry
