import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'ell',
  displayName: 'ELL Census Method (Elbers–Lanjouw–Lanjouw)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['poverty', 'continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'unit',
    weights: true,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'bootstrap',
  rPackage: 'povmap / sae',
  rFunction: '(see ELL procedure in Corral et al. 2022)',
  stataPackage: 'World Bank sae package',
  stataCommand: 'sae model / sae sim / sae quantiles',
  stataMinVersion: 17,
  stataV14Fallback:
    '* The World Bank sae package requires Stata 17+ for the ELL/EB workflow.\n' +
    '* For Stata 14, use the R script (povmap package) or the older PovMap software\n' +
    '* from the World Bank (standalone application, no Stata version requirement).',
  plainDescription:
    'The original World Bank poverty-mapping method. Estimates a welfare model on the survey, ' +
    'decomposes residuals into location and household components, then simulates many welfare ' +
    'vectors onto the census to produce poverty and inequality measures for each area. ' +
    'Superseded by EBP/CensusEB in precision, but still widely used where EBP assumptions ' +
    'are harder to meet.',
  whyChooseThis:
    'Use ELL when the EBP\'s normality assumption is difficult to satisfy, or when following ' +
    'an established institutional protocol. For new analyses, EBP/CensusEB is generally preferred.',
  assumptions: [
    'The two-component residual model (location + household) is correctly specified.',
    'Residuals are independently distributed across clusters.',
    'Survey and census share comparable variable definitions and measurement periods.',
  ],
  references: [
    'Elbers, C., Lanjouw, J. & Lanjouw, P. (2003). Econometrica 71(1), 355–364. https://doi.org/10.1111/1468-0262.00416',
    'Corral, P. et al. (2022). Guidelines to SAE for Poverty Mapping. World Bank. http://hdl.handle.net/10986/37728',
    'World Bank PovMap software. https://www.worldbank.org/en/data/datatopics/povmap',
  ],
  caveats: [
    'EBP is statistically superior for most applications; prefer EBP unless required.',
    'Stata requires v17+ via World Bank sae package; use R or PovMap for v14.',
  ],
  rTemplate: `# ============================================================
# ELL Census Method (Elbers–Lanjouw–Lanjouw)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Elbers, Lanjouw & Lanjouw (2003); Corral et al. (2022)
# R packages: povmap / sae
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (unit-level)
# ============================================================

if (!requireNamespace("povmap", quietly = TRUE)) install.packages("povmap")
library(povmap)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")

# ELL: fit welfare model on survey, simulate onto census with two-component residuals.
# Note: povmap implements EBP which supersedes ELL in precision.
# For strict ELL, use the World Bank PovMap software or the World Bank sae Stata
# package (Stata 17+). The ebp() call below uses the EBP approach as the R alternative.
ell_result <- ebp(
  fixed       = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  pop_data    = census_data,
  pop_domains = "{{AREA_ID}}",
  smp_data    = survey_data,
  smp_domains = "{{AREA_ID}}",
  B           = {{N_SIM}},
  MSE         = TRUE
)

summary(ell_result)
print(estimators(ell_result, indicator = "FGT0"))  # poverty headcount
`,
  stataTemplate: `* ============================================================
* ELL Census Method (Elbers–Lanjouw–Lanjouw)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Elbers, Lanjouw & Lanjouw (2003)
* Stata package: World Bank sae (requires Stata 17+)
* Survey data: {{SURVEY_DATA}}
* Census data: {{CENSUS_DATA}} (unit-level)
* ============================================================

* Install World Bank sae package if not available:
* ssc install sae

use "{{SURVEY_DATA}}", clear

* ELL: survey model with two-component residual structure and survey weights
sae model {{TARGET_VAR}} {{AUX_VARS_STATA}} [pw={{WEIGHT_VAR}}], area({{AREA_ID}})

* Simulate welfare onto census with bootstrap replications
sae sim, census("{{CENSUS_DATA}}") ///
    area({{AREA_ID}}) ///
    bootstrap({{N_SIM}}) ///
    quantiles

sae postestimation
`,
}

export default entry
