import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'fh-eblup',
  displayName: 'Fay–Herriot EBLUP (Area-Level)',
  level: 'area',
  inferenceType: 'frequentist',
  targetTypes: ['continuous', 'proportion', 'binary'],
  requiredInputs: {
    microdata: false,
    areaAggregates: true,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'both',
  rPackage: 'sae',
  rFunction: 'eblupFH / mseFH',
  stataPackage: 'fhsae / fayherriot',
  stataCommand: 'fhsae / fayherriot',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'The most widely used area-level SAE method. Combines direct survey estimates with ' +
    'a regression on area-level covariates, adding a random area effect to capture ' +
    'residual between-area variation. Requires only area-level aggregate data — no microdata ' +
    'needed. MSE estimated analytically (Prasad–Rao) or by bootstrap.',
  whyChooseThis:
    'Choose FH when you have only area-level auxiliary data (e.g. census aggregates) and ' +
    'pre-computed direct estimates with their sampling variances. It is the standard starting ' +
    'point for area-level SAE and is well validated in the literature.',
  assumptions: [
    'Sampling variances of the direct estimates are known (or reliably estimated).',
    'The linking model (regression + random area effect) is correctly specified.',
    'Area random effects are normally distributed with constant variance.',
    'There are enough areas (m ≥ 20) for reliable variance component estimation.',
  ],
  references: [
    'Fay, R.E. & Herriot, R.A. (1979). JASA 74, 269–277. https://doi.org/10.1080/01621459.1979.10481623',
    'Prasad, N. & Rao, J. (1990). JASA 85, 163–171. https://doi.org/10.1080/01621459.1990.10474803',
    'Rao, J.N.K. & Molina, I. (2015). Small Area Estimation, 2nd ed. Wiley. Ch. 4. https://onlinelibrary.wiley.com/doi/book/10.1002/9781118735855',
    'Molina, I. & Marhuenda, Y. (2015). The R Journal 7(1). [sae package] https://doi.org/10.32614/RJ-2015-009',
  ],
  rTemplate: `# ============================================================
# Fay–Herriot EBLUP (Area-Level)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Fay & Herriot (1979); Rao & Molina (2015) Ch. 4
# R package: sae (Molina & Marhuenda, 2015)
# Area-level data: {{AREA_DATA}}
# ============================================================

if (!requireNamespace("sae", quietly = TRUE)) install.packages("sae")
library(sae)

area_data <- read.csv("{{AREA_DATA}}")
# Required columns: {{DIRECT_EST_VAR}}, {{DIRECT_VAR_VAR}}, {{AUX_VARS_R}}, {{AREA_ID}}

# Fit FH model and obtain EBLUPs (REML estimation by default)
fh_result <- eblupFH(
  formula = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir  = area_data\${{DIRECT_VAR_VAR}},
  data    = area_data,
  method  = "REML"   # alternatives: "ML", "FH"
)

# MSE estimates (Prasad–Rao analytic)
fh_mse <- mseFH(
  formula = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir  = area_data\${{DIRECT_VAR_VAR}},
  data    = area_data
)

# Combine results
results <- data.frame(
  area   = area_data\${{AREA_ID}},
  direct = area_data\${{DIRECT_EST_VAR}},
  eblup  = fh_result$eblup,
  mse    = fh_mse$mse,
  rmse   = sqrt(fh_mse$mse),
  cv     = sqrt(fh_mse$mse) / fh_result$eblup
)

print(results)
cat("\\nModel fit:\\n"); print(fh_result$fit$estcoef)
cat("Random effects variance:", fh_result$fit$refvar, "\\n")
`,
  stataTemplate: `* ============================================================
* Fay–Herriot EBLUP (Area-Level)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Fay & Herriot (1979)
* Stata package: fhsae (install: net install fhsae from github)
* Area-level data: {{AREA_DATA}}
* ============================================================

* Install fhsae if not available:
* net install fhsae, from("https://raw.github.com/jpazvd/fhsae/master/")

use "{{AREA_DATA}}", clear
* Required variables: {{DIRECT_EST_VAR}}, {{DIRECT_VAR_VAR}}, {{AUX_VARS_STATA}}

fhsae {{DIRECT_EST_VAR}} {{AUX_VARS_STATA}}, ///
    vardir({{DIRECT_VAR_VAR}}) ///
    method(reml)

* Results stored in e(): use ereturn list to inspect
ereturn list
`,
}

export default entry
