import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'glmm-binary',
  displayName: 'GLMM-EBP — Binary / Proportion (Logit Link)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['binary', 'proportion'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'bootstrap',
  rPackage: 'lme4 / sae (pbmseebBHF adapted)',
  rFunction: 'glmer (lme4)',
  stataPackage: 'base meglm',
  stataCommand: 'meglm (binomial logit)',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'A generalised linear mixed model with a logit link for binary or proportion outcomes. ' +
    'Fits a random-intercept logistic model on the survey microdata. The area means ' +
    '(proportions) are predicted as the conditional expectation given the estimated random ' +
    'effect and fixed coefficients.',
  whyChooseThis:
    'Use this when your target variable is binary (yes/no) or a proportion (e.g. rate of ' +
    'school attendance, employment rate). It respects the [0,1] range of proportions and ' +
    'uses the correct Bernoulli/binomial likelihood.',
  assumptions: [
    'Logistic model is correctly specified.',
    'Area random effects are normally distributed on the log-odds scale.',
    'Units within each area are conditionally independent given the random effect.',
  ],
  references: [
    'Jiang, J. & Lahiri, P. (2001). Ann. Inst. Statistical Mathematics 53, 217–243. https://doi.org/10.1023/A:1017553022248',
    'Jiang, J. (2003). Journal of Statistical Planning and Inference 111, 117–127. https://doi.org/10.1016/S0378-3758(02)00196-2',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.6.7. https://www.fao.org/3/i4818e/i4818e.pdf',
  ],
  rTemplate: `# ============================================================
# GLMM-EBP — Binary / Proportion (Logit)
# Generated by SAE Syntax Generator on {{DATE}}
# R package: lme4
# Reference: Jiang & Lahiri (2001)
# Survey data: {{SURVEY_DATA}}
# ============================================================

if (!requireNamespace("lme4", quietly = TRUE)) install.packages("lme4")
library(lme4)

survey_data <- read.csv("{{SURVEY_DATA}}")

# Fit random-intercept logistic model
glmm_fit <- glmer(
  {{TARGET_VAR}} ~ {{AUX_VARS_R}} + (1 | {{AREA_ID}}),
  data   = survey_data,
  family = binomial(link = "logit")
)
summary(glmm_fit)

# Predicted area proportions
# For sampled areas: conditional on the estimated random effect
# For out-of-sample areas: marginal (random effect = 0)
ranef_vals <- ranef(glmm_fit)\${{AREA_ID}}
fixef_vals <- fixef(glmm_fit)

cat("Area-level predicted proportions can be computed using predict(glmm_fit) or\\n")
cat("by manually applying the inverse logit to: X_bar_i * beta + u_hat_i\\n")
# See Rao & Molina (2015) Ch. 9 for the full EBP derivation for binary models
`,
  stataTemplate: `* ============================================================
* GLMM-EBP — Binary / Proportion (Logit)
* Generated by SAE Syntax Generator on {{DATE}}
* Uses base Stata \`meglm\` — compatible with Stata 14+
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear

meglm {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, family(bernoulli) link(logit)

* Predicted proportions per area
predict p_hat, mu
collapse (mean) p_hat, by({{AREA_ID}})
list
`,
}

export default entry
