import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'glmm-count',
  displayName: 'GLMM-EBP — Count Data (Poisson / Log Link)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['count'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'bootstrap',
  rPackage: 'lme4',
  rFunction: 'glmer (Poisson)',
  stataPackage: 'base meglm',
  stataCommand: 'meglm (Poisson log)',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'A generalised linear mixed model with a Poisson distribution and log link for count ' +
    'outcomes (e.g. number of events per household or area). Includes random area effects ' +
    'to capture between-area heterogeneity beyond the Poisson mean.',
  whyChooseThis:
    'Use this when your target variable is a count (non-negative integer). If the data ' +
    'show more zeros than a Poisson model predicts, consider the two-part / zero-inflated ' +
    'method instead.',
  assumptions: [
    'Poisson distribution is appropriate (no overdispersion; check with dispersion test).',
    'Log-linear model is correctly specified.',
    'Area random effects are normally distributed on the log scale.',
  ],
  references: [
    'Jiang, J. (2003). Journal of Statistical Planning and Inference 111, 117–127.',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.6.7.',
  ],
  rTemplate: `# ============================================================
# GLMM-EBP — Count Data (Poisson / Log Link)
# Generated by SAE Syntax Generator on {{DATE}}
# R package: lme4
# Reference: Jiang (2003)
# Survey data: {{SURVEY_DATA}}
# ============================================================

if (!requireNamespace("lme4", quietly = TRUE)) install.packages("lme4")
library(lme4)

survey_data <- read.csv("{{SURVEY_DATA}}")

# Fit random-intercept Poisson model
glmm_count_fit <- glmer(
  {{TARGET_VAR}} ~ {{AUX_VARS_R}} + (1 | {{AREA_ID}}),
  data   = survey_data,
  family = poisson(link = "log")
)
summary(glmm_count_fit)

# Predicted area counts (conditional on estimated random effect)
# For out-of-sample areas: marginal prediction (random effect = 0)
ranef_count <- ranef(glmm_count_fit)\${{AREA_ID}}
fixef_count <- fixef(glmm_count_fit)

cat("Area-level predicted counts can be computed via predict(glmm_count_fit) or\\n")
cat("by manually applying exp() to: X_bar_i * beta + u_hat_i\\n")
# If excess zeros are present, consider the two-part model (id: two-part-zinfl)
`,
  stataTemplate: `* ============================================================
* GLMM-EBP — Count Data (Poisson / Log Link)
* Generated by SAE Syntax Generator on {{DATE}}
* Uses base Stata \`meglm\` — compatible with Stata 14+
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear

meglm {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, family(poisson) link(log)

* Predicted counts per area
predict lambda_hat, mu
collapse (mean) lambda_hat, by({{AREA_ID}})
list

* If excess zeros are present, consider the two-part/zero-inflated model instead.
`,
}

export default entry
