import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'greg',
  displayName: 'GREG — Generalised Regression Estimator',
  level: 'model-assisted',
  inferenceType: 'design-based',
  targetTypes: ['continuous', 'binary', 'proportion', 'count'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: true,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'prasad-rao',
  rPackage: 'survey / JoSAE',
  rFunction: 'svyglm / eblup.mse.f.wrap',
  stataPackage: 'base',
  stataCommand: 'svy: regress',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'A model-assisted estimator that uses a regression model fitted to the survey microdata, ' +
    'calibrated so that estimates remain design-consistent. Improves on the direct estimator ' +
    'when auxiliary variables are correlated with the target. Area-level means of auxiliaries ' +
    'must be known for the whole population.',
  whyChooseThis:
    'A good first step beyond direct estimation. Requires only area-level auxiliary totals/means ' +
    '(not full census microdata) and remains design-unbiased even if the model is wrong.',
  assumptions: [
    'Regression model is approximately correctly specified.',
    'Area-level population means of auxiliary variables are known without error.',
    'Survey weights are correct.',
  ],
  references: [
    'Rao, J.N.K. & Molina, I. (2015). Small Area Estimation, 2nd ed. Wiley. Ch. 3. https://onlinelibrary.wiley.com/doi/book/10.1002/9781118735855',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.3. https://www.fao.org/3/i4818e/i4818e.pdf',
  ],
  rTemplate: `# ============================================================
# GREG — Generalised Regression Estimator
# Generated by SAE Syntax Generator on {{DATE}}
# Survey data:     {{SURVEY_DATA}}
# Area-level data: {{AREA_DATA}}
# ============================================================

if (!requireNamespace("survey", quietly = TRUE)) install.packages("survey")
library(survey)

survey_data <- read.csv("{{SURVEY_DATA}}")
area_data   <- read.csv("{{AREA_DATA}}")   # must contain {{AREA_ID}} + auxiliary population means

design <- svydesign(ids = ~1, weights = ~{{WEIGHT_VAR}}, data = survey_data)

# Fit regression model
greg_model <- svyglm({{TARGET_VAR}} ~ {{AUX_VARS_R}}, design = design)

# GREG estimate per area (calibration approach)
# Area-level calibration requires the population means in area_data
# See Rao & Molina (2015) Ch. 3 for the manual calibration formula
# or use the JoSAE package eblup.mse.f.wrap() for a wrapper
cat("Model summary:\\n"); summary(greg_model)
`,
  stataTemplate: `* ============================================================
* GREG — Generalised Regression Estimator
* Generated by SAE Syntax Generator on {{DATE}}
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear
svyset [pweight = {{WEIGHT_VAR}}]

svy: regress {{TARGET_VAR}} {{AUX_VARS_STATA}}

* Calibrate by area using postestimation margins
margins {{AREA_ID}}
`,
}

export default entry
