import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'hb-fh',
  displayName: 'Hierarchical Bayes Fay–Herriot (Area-Level)',
  level: 'area',
  inferenceType: 'bayesian',
  targetTypes: ['continuous', 'binary', 'proportion', 'count'],
  requiredInputs: {
    microdata: false,
    areaAggregates: true,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'posterior',
  rPackage: 'saeHB',
  rFunction: 'hbFH (Normal) / hbFH.Beta / hbFH.Poisson',
  stataPackage: 'base',
  stataCommand: '(no direct Stata equivalent; use R)',
  stataMinVersion: 14,
  stataV14Fallback:
    '* No direct Stata equivalent for HB-FH. Run the R script for this method.\n' +
    '* As a Stata-based alternative, use the standard Fay-Herriot model:\n' +
    '* fhsae {{DIRECT_EST_VAR}} {{AUX_VARS_STATA}}, vardir({{DIRECT_VAR_VAR}}) method(reml)',
  plainDescription:
    'A fully Bayesian version of the Fay–Herriot model estimated via MCMC. Provides exact ' +
    'small-sample inference without relying on asymptotic arguments, naturally quantifies ' +
    'all uncertainty including that from hyperparameter estimation, and supports out-of-sample ' +
    'areas through the predictive distribution.',
  whyChooseThis:
    'Choose HB when sample sizes per area are very small (ni < 5), when you need probability ' +
    'statements about the estimates (e.g. P(poverty rate > 30%)), or when the target is ' +
    'binary or a count and a GLMM area-level model is needed.',
  assumptions: [
    'Prior distributions are correctly specified (check sensitivity).',
    'MCMC chains have converged (inspect trace plots and R-hat statistics).',
    'Likelihood model (Normal/Beta/Poisson) suits the data.',
  ],
  references: [
    'Rao & Molina (2015). Small Area Estimation, 2nd ed. Ch. 10.',
    'Datta, G.S. & Ghosh, M. (1991). Annals of Statistics 19, 1748–1770.',
    'saeHB package: CRAN, https://cran.r-project.org/package=saeHB',
  ],
  caveats: [
    'MCMC can be slow for many areas or complex models.',
    'No direct Stata equivalent; R is required.',
  ],
  rTemplate: `# ============================================================
# Hierarchical Bayes Fay–Herriot
# Generated by SAE Syntax Generator on {{DATE}}
# R package: saeHB
# Reference: Rao & Molina (2015) Ch. 10
# Area-level data: {{AREA_DATA}}
# ============================================================

if (!requireNamespace("saeHB", quietly = TRUE)) install.packages("saeHB")
library(saeHB)

area_data <- read.csv("{{AREA_DATA}}")

# Normal HB-FH (use hbFH.Beta for proportions, hbFH.Poisson for counts)
hb_result <- hbFH(
  formula     = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir      = area_data\${{DIRECT_VAR_VAR}},
  data        = area_data,
  iter.update = 3,
  iter.mcmc   = {{N_SIM}},
  thin        = 3,
  burn.in     = 10000
)

summary(hb_result)
# Posterior mean and SD are the point estimate and uncertainty measure
`,
  stataTemplate: `* ============================================================
* Hierarchical Bayes Fay–Herriot — No Direct Stata Equivalent
* Generated by SAE Syntax Generator on {{DATE}}
* Please use the R script (saeHB package) for this method.
* Area-level data: {{AREA_DATA}}
* ============================================================

* HB-FH requires MCMC estimation; no standard Stata implementation exists.
* As a frequentist alternative, use the standard Fay–Herriot model below.
*
* net install fhsae, from("https://raw.github.com/jpazvd/fhsae/master/")

use "{{AREA_DATA}}", clear
fhsae {{DIRECT_EST_VAR}} {{AUX_VARS_STATA}}, vardir({{DIRECT_VAR_VAR}}) method(reml)
ereturn list
`,
}

export default entry
