import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'hb-unit',
  displayName: 'Hierarchical Bayes Unit-Level',
  level: 'unit',
  inferenceType: 'bayesian',
  targetTypes: ['continuous', 'binary', 'proportion', 'count', 'poverty'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'posterior',
  rPackage: 'saeHB / hbsae / BayesSAE',
  rFunction: 'hbNormal / hbBeta / hbPoisson',
  stataPackage: 'base',
  stataCommand: '(no direct Stata equivalent; use R)',
  stataMinVersion: 14,
  stataV14Fallback:
    '* No Stata equivalent for HB unit-level. Use R (saeHB package).\n' +
    '* Stata frequentist approximation:\n' +
    '* mixed {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, reml',
  plainDescription:
    'Fully Bayesian unit-level model estimated via MCMC. Handles all outcome types, provides ' +
    'exact small-sample posterior distributions, supports out-of-sample areas, and quantifies ' +
    'all sources of uncertainty coherently. Particularly suited to sparse data or settings ' +
    'where probability statements about estimates are needed.',
  whyChooseThis:
    'Use HB when: sample sizes per area are very small (ni < 5), you need posterior ' +
    'probability statements (e.g. probability poverty rate exceeds a threshold), or the ' +
    'target requires a non-Gaussian likelihood that is difficult to handle with REML.',
  assumptions: [
    'Prior distributions are appropriately specified and sensitivity-checked.',
    'MCMC chains have converged (check R-hat, effective sample size).',
    'The chosen likelihood (Normal/Beta/Poisson) suits the data.',
  ],
  references: [
    'Rao & Molina (2015). Small Area Estimation, 2nd ed. Ch. 10–11.',
    'Datta, G.S. & Ghosh, M. (1991). Annals of Statistics 19, 1748–1770.',
    'saeHB package: https://cran.r-project.org/package=saeHB',
  ],
  caveats: [
    'MCMC is computationally intensive for large areas or complex models.',
    'No Stata equivalent; R is required for this method.',
  ],
  rTemplate: `# ============================================================
# Hierarchical Bayes Unit-Level
# Generated by SAE Syntax Generator on {{DATE}}
# R package: saeHB (https://cran.r-project.org/package=saeHB)
# Reference: Rao & Molina (2015) Ch. 10-11
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level auxiliary means)
# ============================================================

if (!requireNamespace("saeHB", quietly = TRUE)) install.packages("saeHB")
library(saeHB)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")
# census_data must contain {{AREA_ID}}, population size (Ni),
# and population means of {{AUX_VARS_R}}

# HB unit-level Normal model — use hbBeta for proportions, hbPoisson for counts
hb_result <- hbNormal(
  formula     = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  dom         = survey_data\${{AREA_ID}},
  Ni          = census_data$Ni,
  Xmean       = census_data[, c({{AUX_VARS_R_VEC}})],
  data        = survey_data,
  iter.update = 3,
  iter.mcmc   = {{N_SIM}},
  thin        = 3,
  burn.in     = 10000
)

summary(hb_result)
# hb_result$Est gives posterior means (point estimates per area)
# hb_result$SD  gives posterior standard deviations (uncertainty measure)
`,
  stataTemplate: `* ============================================================
* Hierarchical Bayes Unit-Level — No Direct Stata Equivalent
* Generated by SAE Syntax Generator on {{DATE}}
* Please use the R script (saeHB package) for this method.
* Survey data: {{SURVEY_DATA}}
* ============================================================

* HB unit-level requires MCMC estimation; no standard Stata implementation exists.
* As a frequentist alternative, use the BHF nested-error model:

use "{{SURVEY_DATA}}", clear
mixed {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, reml
`,
}

export default entry
