import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'm-quantile',
  displayName: 'M-Quantile Estimator (Unit-Level, Robust)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: true,
  mseMethod: 'bootstrap',
  rPackage: 'sae (mq functions) / mquantreg',
  rFunction: 'mq_function (SAMPLE project)',
  stataPackage: 'base',
  stataCommand: '(no standard package; implement manually or use R)',
  stataMinVersion: 14,
  stataV14Fallback:
    '* No standard Stata package for M-quantile SAE.\n' +
    '* Use the R script. As a Stata fallback, robust regression with rreg provides\n' +
    '* a related but simplified estimator:\n' +
    '* rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}',
  plainDescription:
    'A robust, distribution-free alternative to the EBLUP. Instead of area random effects, ' +
    'it uses M-quantile coefficients to characterise between-area differences. Performs well ' +
    'when outliers are present or normality is questionable. Does not assume a specific ' +
    'parametric distribution for the residuals.',
  whyChooseThis:
    'Choose M-quantile when you are unsure about the normality of residuals, suspect ' +
    'outliers in the survey data, or want a method that does not rely on strong distributional ' +
    'assumptions. It is often used as a robustness check alongside EBLUP.',
  assumptions: [
    'A smooth relationship exists between the target and auxiliary variables.',
    'The M-quantile coefficients adequately capture between-area variation.',
    'Population means of auxiliary variables are known for all target areas.',
  ],
  references: [
    'Chambers, R. & Tzavidis, N. (2006). Biometrika 93, 255–268.',
    'Marchetti, S., Tzavidis, N. & Pratesi, M. (2012). CSDA 56, 2889–2902.',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.5.3.',
  ],
  rTemplate: `# ============================================================
# M-Quantile Estimator (Unit-Level, Robust)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Chambers & Tzavidis (2006); Marchetti et al. (2012)
# R packages: sae (mq functions) / mquantreg
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level auxiliary means)
# ============================================================

# Option 1: SAMPLE project code (contact Salvati/Tzavidis for mq.sae functions)
# Option 2: mquantreg package for M-quantile regression
if (!requireNamespace("mquantreg", quietly = TRUE)) install.packages("mquantreg")
library(mquantreg)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")
# census_data must contain {{AREA_ID}} and population means of {{AUX_VARS_R}}

# Step 1: Fit M-quantile regression on survey data
mq_fit <- mquantreg(
  formula = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  data    = survey_data,
  q       = 0.5,       # global median; area-specific q_i estimated internally
  psi     = "Huber"    # influence function
)

# Step 2: Estimate area-specific M-quantile coefficients (theta_i)
# theta_i represents the quantile level most representative of area i
theta_i <- tapply(
  predict(mq_fit) - survey_data\${{TARGET_VAR}},
  survey_data\${{AREA_ID}},
  function(r) mean(r >= 0)
)
cat("Area M-quantile coefficients (theta_i):\\n"); print(theta_i)

# Step 3: Bootstrap MSE (B = {{N_SIM}} replications)
# See Marchetti, Tzavidis & Pratesi (2012) CSDA 56, 2889-2902 for MSE procedure
cat("For MSE: parametric bootstrap with B =", {{N_SIM}}, "replications.\\n")
`,
  stataTemplate: `* ============================================================
* M-Quantile Estimator (Unit-Level, Robust)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Chambers & Tzavidis (2006)
* Note: No standard Stata package; use R for the full M-quantile estimator.
* Survey data: {{SURVEY_DATA}}
* ============================================================

* M-quantile SAE has no standard Stata package.
* The following uses robust regression (rreg) as a simplified alternative.
* For the proper M-quantile estimator, use the R script.

use "{{SURVEY_DATA}}", clear
rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}

* For MSE, bootstrap with B = {{N_SIM}} replications.
* Reference: Chambers & Tzavidis (2006) Biometrika 93, 255-268
`,
}

export default entry
