import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'mqgwr',
  displayName: 'M-Quantile GWR (Unit-Level, Robust + Spatial)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: true,
  },
  spatial: true,
  robust: true,
  mseMethod: 'bootstrap',
  rPackage: 'SAMPLE project functions (mqgwr.sae)',
  rFunction: 'mqgwr.sae',
  stataPackage: 'base',
  stataCommand: '(no standard Stata package; use R)',
  stataMinVersion: 14,
  stataV14Fallback:
    '* No Stata equivalent for MQGWR. Use R. As a spatial approximation in Stata:\n' +
    '* rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}',
  plainDescription:
    'Combines M-quantile regression with geographically weighted regression (GWR) to handle ' +
    'both outliers and spatial non-stationarity. Each area gets its own locally fitted ' +
    'regression, weighted by distance to neighbouring areas. Requires unit coordinates or ' +
    'area centroids.',
  whyChooseThis:
    'Use MQGWR when you have geographic coordinates and suspect that the relationship between ' +
    'the target and auxiliary variables varies across space (spatial non-stationarity) in ' +
    'addition to possible outliers.',
  assumptions: [
    'M-quantile assumptions hold locally.',
    'Spatial relationship between units can be captured by a Euclidean distance kernel.',
    'Coordinates (centroids) are available for sampled and non-sampled areas.',
  ],
  references: [
    'Salvati, N. et al. (2012). CSDA 56, 2875–2888. https://doi.org/10.1016/j.csda.2011.11.006',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.5.4. https://www.fao.org/3/i4818e/i4818e.pdf',
  ],
  rTemplate: `# ============================================================
# M-Quantile GWR (Unit-Level, Robust + Spatial)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Salvati et al. (2012) CSDA 56, 2875-2888
# R package: SAMPLE project functions (mqgwr.sae)
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level auxiliary means + centroids)
# ============================================================

# MQGWR requires the SAMPLE project implementation.
# Contact the authors (Salvati, Ranalli, Pratesi) or obtain mqgwr.sae().

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")
# census_data must contain {{AREA_ID}}, means of {{AUX_VARS_R}}, and lat/lon centroids

# Area centroid coordinates (replace 'lat' and 'lon' with actual column names)
coords_smp  <- cbind(survey_data$lat, survey_data$lon)
coords_pop  <- cbind(census_data$lat, census_data$lon)

# Calling convention (adjust to actual SAMPLE project function signature):
# mqgwr.sae(
#   y        = survey_data\${{TARGET_VAR}},
#   X        = model.matrix(~ {{AUX_VARS_R}}, data = survey_data),
#   area     = survey_data\${{AREA_ID}},
#   coords   = coords_smp,
#   cens.X   = model.matrix(~ {{AUX_VARS_R}}, data = census_data),
#   cens.coords = coords_pop,
#   B        = {{N_SIM}}
# )

cat("MQGWR: spatial + robust estimation for {{AREA_ID}}, target {{TARGET_VAR}}.\\n")
cat("Bootstrap replications: {{N_SIM}}.\\n")
cat("See Salvati et al. (2012) CSDA 56, 2875-2888 for full implementation details.\\n")
`,
  stataTemplate: `* ============================================================
* M-Quantile GWR (Unit-Level, Robust + Spatial)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Salvati et al. (2012)
* Note: No Stata package for MQGWR; use R (SAMPLE project functions).
* Survey data: {{SURVEY_DATA}}
* ============================================================

* MQGWR has no standard Stata package.
* As a simplified robust alternative, use rreg below.
* For the full MQGWR estimator, use the R script.

use "{{SURVEY_DATA}}", clear
rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}

* For spatial component, see Salvati et al. (2012) CSDA 56, 2875-2888
* Centroid coordinates should be available in {{AREA_DATA}}
`,
}

export default entry
