import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'reblup',
  displayName: 'Robust EBLUP — REBLUP (Unit-Level)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: true,
  mseMethod: 'bootstrap',
  rPackage: 'saeRobust',
  rFunction: 'reblup',
  stataPackage: 'base',
  stataCommand: '(no standard Stata package; use R)',
  stataMinVersion: 14,
  stataV14Fallback:
    '* No standard Stata equivalent for REBLUP. Use the R script.\n' +
    '* Stata approximation using robust regression:\n' +
    '* rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}',
  plainDescription:
    'An outlier-robust version of the nested-error EBLUP. Uses Huber\'s influence function ' +
    'to downweight influential observations when estimating fixed effects and variance ' +
    'components, making the estimator robust to departures from normality at the unit level.',
  whyChooseThis:
    'Choose REBLUP when you want the modelling framework of the BHF model but are concerned ' +
    'about outlying units inflating estimates. Performs similarly to M-quantile in most ' +
    'scenarios; use REBLUP if you prefer a mixed-model framework.',
  assumptions: [
    'The majority of units follow the nested-error linear model.',
    'A small proportion of units are outliers; Huber tuning constant c = 1.345 is appropriate.',
  ],
  references: [
    'Sinha, S.K. & Rao, J.N.K. (2009). Canadian Journal of Statistics 37, 381–399.',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 5.2.2.',
  ],
  rTemplate: `# ============================================================
# Robust EBLUP (REBLUP) — Sinha–Rao
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Sinha & Rao (2009)
# R package: saeRobust
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level auxiliary means)
# ============================================================

if (!requireNamespace("saeRobust", quietly = TRUE)) install.packages("saeRobust")
library(saeRobust)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")
# census_data must contain {{AREA_ID}} and population means of {{AUX_VARS_R}}

# Fit REBLUP: robustified nested-error linear mixed model
# Huber's influence function downweights outlying units (default c = 1.345)
reblup_result <- reblup(
  formula  = {{TARGET_VAR}} ~ {{AUX_VARS_R}},
  domain   = survey_data\${{AREA_ID}},
  sizedom  = census_data$Ni,
  meanxpop = census_data[, c({{AUX_VARS_R_QUOTED}})],
  data     = survey_data
)

summary(reblup_result)

# Bootstrap MSE (B = {{N_SIM}} replications)
reblup_mse <- mse(reblup_result, type = "pseudo", B = {{N_SIM}})
print(reblup_mse)
`,
  stataTemplate: `* ============================================================
* Robust EBLUP (REBLUP) — Sinha–Rao
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Sinha & Rao (2009)
* Note: No standard Stata package; use R (saeRobust) for the full estimator.
* Survey data: {{SURVEY_DATA}}
* ============================================================

* REBLUP has no standard Stata package.
* The following robust regression (rreg) is a simplified alternative.
* For the proper REBLUP estimator, use the R script (saeRobust::reblup).

use "{{SURVEY_DATA}}", clear
rreg {{TARGET_VAR}} {{AUX_VARS_STATA}} i.{{AREA_ID}}
`,
}

export default entry
