import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'robust-fh',
  displayName: 'Robust Fay–Herriot (Area-Level)',
  level: 'area',
  inferenceType: 'frequentist',
  targetTypes: ['continuous'],
  requiredInputs: {
    microdata: false,
    areaAggregates: true,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: true,
  mseMethod: 'bootstrap',
  rPackage: 'saeRobust',
  rFunction: 'rfh',
  stataPackage: 'fhsae',
  stataCommand: 'fhsae with robust option',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'A robustified version of the Fay–Herriot model that downweights outlying areas. ' +
    'Useful when a small number of areas have direct estimates that are unusually far from ' +
    'the model predictions, which would otherwise distort the variance component estimates.',
  whyChooseThis:
    'Choose this when you suspect a few areas are atypical or when diagnostic plots for ' +
    'the standard FH model show heavy-tailed residuals or influential observations.',
  assumptions: [
    'Same as standard FH, except normality of random effects is relaxed.',
    'A small proportion of areas are outliers; the majority follow the FH model.',
  ],
  references: [
    'Chambers, R. & Tzavidis, N. (2006). Biometrika 93, 255–268. https://doi.org/10.1093/biomet/93.2.255',
    'Sinha, S.K. & Rao, J.N.K. (2009). Canadian Journal of Statistics 37, 381–399. https://doi.org/10.1002/cjs.10007',
    'Rao, J.N.K. & Molina, I. (2015). Small Area Estimation, 2nd ed. Wiley. Ch. 7. https://onlinelibrary.wiley.com/doi/book/10.1002/9781118735855',
  ],
  rTemplate: `# ============================================================
# Robust Fay–Herriot
# Generated by SAE Syntax Generator on {{DATE}}
# R package: saeRobust
# Area-level data: {{AREA_DATA}}
# ============================================================

if (!requireNamespace("saeRobust", quietly = TRUE)) install.packages("saeRobust")
library(saeRobust)

area_data <- read.csv("{{AREA_DATA}}")

rfh_result <- rfh(
  formula = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir  = "{{DIRECT_VAR_VAR}}",
  data    = area_data
)
summary(rfh_result)

# Bootstrap MSE (B = {{N_SIM}} replications)
rfh_mse <- mse(rfh_result, type = "pseudo", B = {{N_SIM}})
print(rfh_mse)
`,
  stataTemplate: `* ============================================================
* Robust Fay–Herriot (Area-Level)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Sinha & Rao (2009)
* Stata package: fhsae
* Area-level data: {{AREA_DATA}}
* ============================================================

* Install fhsae if not available:
* net install fhsae, from("https://raw.github.com/jpazvd/fhsae/master/")

use "{{AREA_DATA}}", clear

fhsae {{DIRECT_EST_VAR}} {{AUX_VARS_STATA}}, ///
    vardir({{DIRECT_VAR_VAR}}) ///
    robust ///
    method(reml)

ereturn list
`,
}

export default entry
