import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'spatial-fh',
  displayName: 'Spatial Fay–Herriot EBLUP (Area-Level, SAR)',
  level: 'area',
  inferenceType: 'frequentist',
  targetTypes: ['continuous', 'proportion'],
  requiredInputs: {
    microdata: false,
    areaAggregates: true,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: true,
    coordinates: false,
  },
  spatial: true,
  robust: false,
  mseMethod: 'both',
  rPackage: 'sae',
  rFunction: 'eblupSFH / mseSFH',
  stataPackage: 'fhsae',
  stataCommand: 'fhsae with spatialcor option',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'Extends the Fay–Herriot model by allowing area random effects to be spatially correlated ' +
    'via a simultaneous autoregressive (SAR) model. Reduces MSE when neighbouring areas share ' +
    'characteristics. Requires a spatial contiguity or distance matrix.',
  whyChooseThis:
    'Choose this over standard FH when your areas are geographically contiguous and you expect ' +
    'similar areas to have similar values (e.g. neighbouring districts in a country). The spatial ' +
    'model borrows strength across neighbouring areas as well as from auxiliaries.',
  assumptions: [
    'All FH assumptions hold.',
    'The SAR spatial structure correctly captures the spatial dependence.',
    'The contiguity matrix correctly represents neighbourhood relationships.',
  ],
  references: [
    'Pratesi, M. & Salvati, N. (2008). Statistical Methods and Applications 17, 113–141.',
    'Singh, B. et al. (2005). Survey Methodology 31(1), 33–40.',
    'Rao & Molina (2015). Small Area Estimation, 2nd ed. Ch. 8.',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 2.4.3.',
  ],
  caveats: [
    'Constructing the contiguity matrix requires GIS boundary files or coordinates.',
    'With few areas (m < 15), spatial parameter estimation is unreliable.',
  ],
  rTemplate: `# ============================================================
# Spatial Fay–Herriot EBLUP (SAR area effects)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Pratesi & Salvati (2008)
# R package: sae
# Area-level data: {{AREA_DATA}}
# Contiguity matrix: {{CONTIG_MATRIX}}
# ============================================================

if (!requireNamespace("sae", quietly = TRUE)) install.packages("sae")
if (!requireNamespace("spdep", quietly = TRUE)) install.packages("spdep")
library(sae); library(spdep)

area_data <- read.csv("{{AREA_DATA}}")
# Load contiguity matrix (row-standardised, nb or matrix object)
# Example: W <- nb2mat(poly2nb(your_shapefile), style = "W")
W <- as.matrix(read.csv("{{CONTIG_MATRIX}}", row.names = 1))

sfh_result <- eblupSFH(
  formula = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir  = area_data\${{DIRECT_VAR_VAR}},
  proxmat = W,
  data    = area_data,
  method  = "REML"
)

sfh_mse <- mseSFH(
  formula = {{DIRECT_EST_VAR}} ~ {{AUX_VARS_R}},
  vardir  = area_data\${{DIRECT_VAR_VAR}},
  proxmat = W,
  data    = area_data
)

results <- data.frame(
  area  = area_data\${{AREA_ID}},
  eblup = sfh_result$eblup,
  mse   = sfh_mse$mse,
  cv    = sqrt(sfh_mse$mse) / sfh_result$eblup
)
print(results)
`,
  stataTemplate: `* ============================================================
* Spatial Fay–Herriot EBLUP (SAR)
* Generated by SAE Syntax Generator on {{DATE}}
* Reference: Pratesi & Salvati (2008)
* Stata package: fhsae
* Area-level data: {{AREA_DATA}}
* Contiguity matrix: {{CONTIG_MATRIX}}
* ============================================================

* Install fhsae if not available:
* net install fhsae, from("https://raw.github.com/jpazvd/fhsae/master/")

use "{{AREA_DATA}}", clear

* Load spatial weights matrix (row-standardised)
* See fhsae documentation for spatialcor option syntax
fhsae {{DIRECT_EST_VAR}} {{AUX_VARS_STATA}}, ///
    vardir({{DIRECT_VAR_VAR}}) ///
    spatialcor({{CONTIG_MATRIX}}) ///
    method(reml)

ereturn list
`,
}

export default entry
