import type { CatalogueEntry } from '../types/index.js'

const entry: CatalogueEntry = {
  id: 'two-part-zinfl',
  displayName: 'Two-Part / Zero-Inflated Model (Unit-Level)',
  level: 'unit',
  inferenceType: 'frequentist',
  targetTypes: ['count', 'continuous'],
  requiredInputs: {
    microdata: true,
    areaAggregates: false,
    censusAuxiliaries: 'area',
    weights: false,
    contiguityMatrix: false,
    coordinates: false,
  },
  spatial: false,
  robust: false,
  mseMethod: 'bootstrap',
  rPackage: 'lme4 (two-model approach)',
  rFunction: 'glmer (binomial) + glmer/lmer (positive part)',
  stataPackage: 'base',
  stataCommand: 'meglm (binomial) + meglm/mixed (positive part)',
  stataMinVersion: 14,
  stataV14Fallback: null,
  plainDescription:
    'Handles data with an excess of zeros by fitting two models: (1) a logistic mixed model ' +
    'for the probability of a non-zero outcome, and (2) a linear or count mixed model for ' +
    'the magnitude of non-zero outcomes. The area mean is the product of (1) and (2).',
  whyChooseThis:
    'Use this when your target variable has many zeros — for example, crop yields (many ' +
    'farms grow nothing), health expenditures, or agricultural output — and a standard ' +
    'Poisson or log-normal model does not fit the data.',
  assumptions: [
    'The zero-generating process is distinct from the positive-value process.',
    'Both component models are correctly specified.',
    'Area random effects in both parts may be correlated.',
  ],
  references: [
    'Pfeffermann, D. et al. (2008). Survey Methodology 34, 105–116. https://www150.statcan.gc.ca/n1/pub/12-001-x/2008001/article/10612-eng.pdf',
    'Chandra, H. & Chambers, R. (2014). Computational Statistics 29, 1023–1050. https://doi.org/10.1007/s00180-013-0409-8',
    'FAO (2015). SAE Methods for Agricultural Surveys. Ch. 8. https://www.fao.org/3/i4818e/i4818e.pdf',
  ],
  rTemplate: `# ============================================================
# Two-Part / Zero-Inflated Model (Unit-Level)
# Generated by SAE Syntax Generator on {{DATE}}
# Reference: Pfeffermann et al. (2008); Chandra & Chambers (2014)
# R package: lme4 (two-model approach)
# Survey data: {{SURVEY_DATA}}
# Census data: {{CENSUS_DATA}} (area-level auxiliary means)
# ============================================================

if (!requireNamespace("lme4", quietly = TRUE)) install.packages("lme4")
library(lme4)

survey_data <- read.csv("{{SURVEY_DATA}}")
census_data <- read.csv("{{CENSUS_DATA}}")

# Part 1: Logistic mixed model for P(Y > 0)
survey_data$y_pos <- as.integer(survey_data\${{TARGET_VAR}} > 0)
part1_fit <- glmer(
  y_pos ~ {{AUX_VARS_R}} + (1 | {{AREA_ID}}),
  data   = survey_data,
  family = binomial(link = "logit")
)

# Part 2: Linear mixed model for E(Y | Y > 0)
positive_data <- survey_data[survey_data\${{TARGET_VAR}} > 0, ]
part2_fit <- lmer(
  {{TARGET_VAR}} ~ {{AUX_VARS_R}} + (1 | {{AREA_ID}}),
  data = positive_data,
  REML = TRUE
)

# Area mean = P(Y > 0) * E(Y | Y > 0)
p_nonzero  <- predict(part1_fit, newdata = census_data, type = "response", re.form = NA)
e_positive <- predict(part2_fit, newdata = census_data, re.form = NA)
area_mean  <- p_nonzero * e_positive

results <- data.frame(area = census_data\${{AREA_ID}}, mean_estimate = area_mean)
print(results)

# For bootstrap MSE (B = {{N_SIM}} replications):
# See Pfeffermann et al. (2008) Survey Methodology 34, 105-116
`,
  stataTemplate: `* ============================================================
* Two-Part / Zero-Inflated Model (Unit-Level)
* Generated by SAE Syntax Generator on {{DATE}}
* Uses base Stata \`meglm\` and \`mixed\` — compatible with Stata 14+
* Survey data: {{SURVEY_DATA}}
* ============================================================

use "{{SURVEY_DATA}}", clear

* Part 1: Logistic model for P(Y > 0)
gen y_pos = ({{TARGET_VAR}} > 0)
meglm y_pos {{AUX_VARS_STATA}} || {{AREA_ID}}:, family(bernoulli) link(logit)
predict p_nonzero, mu

* Part 2: Model for E(Y | Y > 0) — run on positive observations only
preserve
keep if {{TARGET_VAR}} > 0
mixed {{TARGET_VAR}} {{AUX_VARS_STATA}} || {{AREA_ID}}:, reml
predict y_pos_hat, xb
restore

* Area mean = P(Y > 0) * E(Y | Y > 0)
* Merge predictions and compute product by {{AREA_ID}}
`,
}

export default entry
